[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
resolver = "2"
members = [
  "program",
]
